### ISSUE TITLE
Having trouble importing my data into the .RDA format dataframe

### ISSUE THREAD

**Issue by orsburn** [dionezhang/pepDESC#1]
Hi DioneZhang,
Super pumped about this tool. I'm still struggling getting my data imported into the dataframe.
Can you provide extra documentation regarding how to move from Excel or CSV into the correct .RDA format? I've pulled your .RDA out through the write.xls package so I see how yours is parsed, but when I read it in I'm missing something.
A direct .csv import into pepDESC would be really useful.
Thanks!

**Comment by dionezhang** [comment]
Generally any package that can transfer .CSV to .RDA would work. For example I used the read.table to import Excel file into the R environment. The problem of data importing in pepDESC is that the result files from different search engines have various column names, therefore, a universal command would be very difficult. So for your situation my suggestion is to import your Excel or CSV data with any possible tool and mannually modify the column names of your .RDA data to fit the Initialization function in pepDESC.
